"""empty message

Revision ID: 091020c9115a
Revises: a8fbc4c90c55
Create Date: 2022-06-28 22:13:04.735495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091020c9115a'
down_revision = 'a8fbc4c90c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('facebook', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('instagram', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'facebook')
    op.drop_column('user', 'twitter')
    # ### end Alembic commands ###
