"""empty message

Revision ID: 16953b80891d
Revises: 51e6073e5a10
Create Date: 2023-05-11 15:05:09.586004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16953b80891d'
down_revision = '51e6073e5a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile_info', schema=None) as batch_op:
        batch_op.drop_column('education')

    # ### end Alembic commands ###
