"""empty message

Revision ID: 17bc6431140f
Revises: 4e7c85c36f38
Create Date: 2022-09-12 21:08:01.091703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bc6431140f'
down_revision = '4e7c85c36f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pais', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pais')
    # ### end Alembic commands ###
