"""empty message

Revision ID: 890f92e918f5
Revises: a6b2cbac5314
Create Date: 2022-06-29 17:32:59.429558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890f92e918f5'
down_revision = 'a6b2cbac5314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_psicologo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_psicologo')
    # ### end Alembic commands ###
