"""empty message

Revision ID: a6b2cbac5314
Revises: 091020c9115a
Create Date: 2022-06-28 22:31:52.164447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b2cbac5314'
down_revision = '091020c9115a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['instagram'])
    op.create_unique_constraint(None, 'user', ['twitter'])
    op.create_unique_constraint(None, 'user', ['facebook'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
