"""empty message

Revision ID: b2a671a967ba
Revises: 5f589cf48dd2
Create Date: 2022-06-17 00:26:56.137200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a671a967ba'
down_revision = '5f589cf48dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('mostrar_nombre', sa.String(length=120), nullable=False),
    sa.Column('area_de_especialidad', sa.String(length=120), nullable=False),
    sa.Column('pais', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
