"""empty message

Revision ID: ccf037845b2a
Revises: aca47986846d
Create Date: 2022-10-10 23:44:46.424716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf037845b2a'
down_revision = 'aca47986846d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_name_key', 'session', type_='unique')
    op.drop_constraint('session_time_key', 'session', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('session_time_key', 'session', ['time'])
    op.create_unique_constraint('session_name_key', 'session', ['name'])
    # ### end Alembic commands ###
